### ISSUE TITLE
Secured Resources Possible?

### ISSUE THREAD

**Issue by rhelsing** [diogob/postgresql_lo_streamer#12]
How do you envision secure resources working?

Right now, all id's are automatically streamed and routes are public. I would ideally like to secure a subset of these id's. I could encrypt certain files, but that is not as secure as I would like. I would like to  be able to check if the current_user is set and if they can access that resource. Any thoughts on this?

**Comment by rhelsing** [comment]
Possibly:

```ruby
#secure version w/ current user object and configuration options on how to process it?
mount PostgresqlLoStreamer::SecureEngine => "/files"
```

I don't know enough about Postgres large objects yet but is it possible to separate the namespace of the sets of id's possibly?

**Comment by rhelsing** [comment]
Then again if only context available to the streamer controller is the current_user and oid, the function to determine authorization could be untenable if having to figure out which rails model the oid is stored on. Either way, let me know if you have any thoughts on this matter.

**Comment by rhelsing** [comment]
Right now, I am leaning towards having to create unique routes for each of my object fields, authorizing when requested, then delegating to some of the functionality provided by your library.. I wonder if I could include pieces of it as a module.

**Comment by rhelsing** [comment]
Here's my plan:

```ruby
#routes.rb
get 'files/:model/:id/:field/:oid-:md5', to: 'files#stream', :as => :files

#/files/employer/12/logo/43116-e6d8adff02df2e1de59102823cec4d3b.png
#files_controller#stream
ActionController::Parameters {"controller"=>"files", "action"=>"stream", "model"=>"employer", "id"=>"12", "field"=>"logo", "oid"=>"43116", "md5"=>"e6d8adff02df2e1de59102823cec4d3b", "format"=>"png"}
#auth w/ context, stream
```

**Comment by diogob** [comment]
It seems to me that the controller provided by this gem is not really reusable for this use case. But you could reuse the logic that creates the enumerator from the database if this was in an extracted class.

Maybe the gem should provide not only the mountable engine, but also a class to stream files out of the database so you can use in custom controllers.

something like:
```ruby
streamer = PostgresqlLoStreamer::LoReader.new(connection, object_id)
self.response_body = streamer
```

This class would be extracted from https://github.com/diogob/postgresql_lo_streamer/blob/master/app/controllers/postgresql_lo_streamer/lo_controller.rb#L15

**Comment by rhelsing** [comment]
That would be perfect. I will let you know if I have any questions while trying it out...
