### ISSUE TITLE
audio files

### ISSUE THREAD

**Issue by jakehockey10** [diogob/postgresql_lo_streamer#14]
I am using `carrierwave-postgresql` along with this gem, and I'm attempting to store audio files.  I'm trying to use an `<audio>` tag to have the songs playable in whatever the browser's rendering of the audio tag is.

I added an initializer that looks like this:

``` ruby
PostgresqlLoStreamer.configure do |config|
  config.options = { type: 'audio/mpeg' }
end
```

However, it looks like this is still assuming it is a `png` file or something.  I can't seem to get this to work.

Do you know how I would get this to work the way I've described?

Thanks!

**Comment by diogob** [comment]
Hi @jakehockey10 , what is the URI you are using on the audio tag?

**Comment by jakehockey10** [comment]
@diogob I'm using the following html in my partial: 

_play.html.erb:
``` erb
<audio class="song-audio" id="<%= song.id %>" controls preload="auto">
  <source src="<%= song.audio2 %>" type="audio/mpeg">
</audio>
```

config/routes.rb:
``` ruby
  mount PostgresqlLoStreamer::Engine => '/song_audio2'
```

Is this because the Mime Type for mp3 or mpeg is not handled?  Do I need to do something in addition to what is shown in the README?

I notice that the response headers are a bit different than I would expect when viewing the network tab in the chrome dev tools:
```
Content-Disposition: attachment
Content-Transfer-Encoding: binary
Content-Type: video/mpeg
```

**Comment by jakehockey10** [comment]
I'm just not sure that this is actually making the file stream.  The reason for using this was so that the audio file would be streamed down so that Chrome's audio tag's seek bar would be correct.  Right now, Chrome's audio control doesn't work correctly because the file isn't being streamed and the Range requests aren't being handled.  Is this the intent of this gem or did I misunderstand?

**Comment by diogob** [comment]
@jakehockey10 the range headers are not handled by this gem, it was designed with images as the primary use case, so it's easier to stream them in one request. Other binary formats would be send to download as attachment, so unfortunately it's not a good fit for your use case.

Having said that, to implement a proper audio streams with range handling you can probably derive your implementation using this file as a base: https://github.com/diogob/postgresql_lo_streamer/blob/master/lib/postgresql_lo_streamer/streamer.rb

**Comment by jakehockey10** [comment]
Thanks @diogob .  I've reversed my decision to move away from s3 and use this approach.  If I go back to using s3, even though I think it is overkill for my usecase, aws servers handled all of this for me.  After upgrading my app to Rails 5.2, I'm probably going to go with the `:amazon` flavor of `active_storage` and call it done.  I really liked perusing the concept of storing these files in my database since I never expect the database to get very large at all, but it became too enticing to delegate some of this work to s3/rails
