### ISSUE TITLE
IE can't decode images?

### ISSUE THREAD

**Issue by DaveSanders** [diogob/postgresql_lo_streamer#3]
I'm using postgresl_lo_streamer, along with carrierwave.

For reasons unknown to me, I get this error in IE 9 / 10 / 11 trying to download an image that works fine in Chrome: 

Failed to open http://data.staging.opf4.com/organization/organization_avatar/2190819

Image url (temporary, it will be going away soon) 

http://data.staging.opf4.com/organization/organization_avatar/2190819

Whats even funnier is that if I go into the IE dev tools, and I run the Network trace, it shows the image there just fine.

If you guys could somehow invent a time machine and keep Internet Explorer from ever happening at all, that would be the ideal solution.   But short of that, I'd happily take other advice.

**Comment by nfedyashev** [comment]
@DaveSanders were you able to fix it or find a workaround?

**Comment by nfedyashev** [comment]
"Unable to decode image at URL" warnings in IE.
I got those solved by adjusting config.action_dispatch.default_headers to exclude "X-Content-Type-Options" header from being sent. All images are visible now in IE.

It has nothing to do with postgresql_lo_streamer
