### ISSUE TITLE
500 exception when file not found

### ISSUE THREAD

**Issue by daudt** [diogob/postgresql_lo_streamer#4]
Whenever I'm trying to retrieve a file from a record that was deleted, the controller returns a 500 status code:

PG::Error (can't open large object: ERROR:  large object 33316 does not exist)

Would it be possible to return a proper 404 for this? Is there a way to customize this?

Thanks!

**Comment by diogob** [comment]
There is no way to customize it, but it's definitely a bug. Will try to fix it over the weekend.

**Comment by edwardmp** [comment]
@daudt @diogob 
Should be fixed in #6

**Comment by edwardmp** [comment]
@diogob you can close this issue :)
