### ISSUE TITLE
Can't configure different mime-types for different endpoints

### ISSUE THREAD

**Issue by Kukunin** [diogob/postgresql_lo_streamer#9]
In my application I have different uploaders: one for images, second for pdf files.

While I can mount the engine multiple times, I can have mount-specific configurations, since everything is stored globally in `PostgresqlLoStreamer.configuration` object. 

This makes it impossible to set `image/png` for one route and `application/pdf` for another.

It also might be not a bad idea to use `https://github.com/minad/mimemagic` gem to determine the correct mime type, because currently it still sets `image/png` by default even for JPG image

**Comment by diogob** [comment]
Having the chance to specify configurations per mount point is an interesting feature. If you are willing to put the time to send a pull request I can help you.

**Comment by rhelsing** [comment]
@diogob @Kukunin See #11

**Comment by diogob** [comment]
@Kukunin I believe the changes introduced by @rhelsing in #11 will solve your use case. They are part of the 1.2.0 release of the gem.
